spravy:
  prefix: "#00C7EESenWorldss &8▸ "
  creatingworld: "{prefix} §7Vytvara sa svet: {name} ..."
  worldcreated: "{prefix} &eSvet {name} bol vytvoreny"

usage:
  noargscreate: "{prefix} &cPouzitie: /sw create <meno> <normal/nether/end/flat/void>"
  helpmessage:
    - " "
    - "&r &r #00C7EE&lSenWorlds &7- #00C7EE&lCommandy:"
    - " "
    - "&r &r #FF2929&l<> &7- Povinné, #16EC00&l[] &7- Voliteľné"
    - " "
    - "&r &r #00C7EE/sw create <meno> <env> &8▸ &7Vytvorí Svet"
    - "&r &r #00C7EE/sw delete <meno> &8▸ &7Zmaže Svet"
    - "&r &r #00C7EE/sw reload &8▸ &7Reloadne Plugin"
    - "&r &r #00C7EE/sw list &8▸ &7Zobrazí Svety"
    - " "

errory:
  zmazanysvettp: "{prefix} &7Svet bol zmazaný. Bol si teleportovaný."
  invalidenv: "{prefix} &7Neplatný Enviroment. Použi: Normal, End, Nether, Flat, Void"
  worldexists: "&7Svet už existuje!"