spravy:
  prefix: "#00C7EESenWorlds &8▸ "

errory:
  zmazanysvettp: "{prefix} &7Svet bol zmazaný. Bol si teleportovaný."
  invalidenv: "&7Neplatný Enviroment. Použi: Normal, End, Nether, Flat, Void"
  worldexists: "&7Svet už existuje!"